name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK (for Java projects)
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Use appropriate Java version
        distribution: 'oracle'
        

    - name: Set up C++ environment (for C++ projects)
      run: sudo apt-get install g++  # Install C++ compiler

    - name: Compile and run Java program if Main.java exists
      id: java-test
      run: |
        if [ -f src/Main.java ]; then
          cd src
          javac Main.java  # Compile Java code
          
          # Run Java program with the input: 1 and the expression "A=2+3"
          result=$(echo "1 A=2+3" | java Main)
          echo "Output: $result"  # Log the result
          
          # Check if the result matches the expected output "A=5"
          if [ "$result" == "A=5" ]; then
            echo "Java sum test passed!"
          else
            echo "Java sum test failed!"
            exit 1
          fi
        else
          echo "No Java program found, skipping Java test."
        fi

    - name: Compile and run C++ program if main.cpp exists
      id: cpp-test
      run: |
        if [ -f src/main.cpp ]; then
          cd src
          g++ -o main main.cpp  # Compile C++ program
          
          # Run C++ program with the input: 1 and the expression "A=2+3"
          result=$(echo "1 A=2+3" | ./main)
          echo "Output: $result"  # Log the result
          
          # Check if the result matches the expected output "A=5"
          if [ "$result" == "A=5" ]; then
            echo "C++ sum test passed!"
          else
            echo "C++ sum test failed!"
            exit 1
          fi
        else
          echo "No C++ program found, skipping C++ test."
        fi

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: |
          java-test  # Include the Java test results
          cpp-test   # Include the C++ test results
