name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK (for Java projects)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up C++ environment (for C++ projects)
      run: sudo apt-get install g++

    - name: Run Java tests
      id: java-test
      run: |
        if [ -f src/Main.java ]; then
          cd src
          javac Main.java
          passed_tests=0
          total_tests=0
          for input_file in ../.github/workflows/testCases/input/*.txt; do
            total_tests=$((total_tests + 1))
            base_name=$(basename "$input_file" .txt)
            output_file="../.github/workflows/testCases/output/${base_name}.txt"
            result=$(java Main < "$input_file")
            expected=$(cat "$output_file")
            if [ "$result" == "$expected" ]; then
              echo "Test $base_name passed"
              passed_tests=$((passed_tests + 1))
            else
              echo "Test $base_name failed. Expected: $expected, Got: $result"
            fi
          done
          echo "Java tests: $passed_tests/$total_tests passed"
          if [ $passed_tests -eq $total_tests ]; then
            echo "All Java tests passed!"
          else
            echo "Some Java tests failed!"
            exit 1
          fi
        else
          echo "No Java program found, skipping Java tests."
        fi

    - name: Run C++ tests
      id: cpp-test
      run: |
        if [ -f src/main.cpp ]; then
          cd src
          g++ -o main main.cpp
          passed_tests=0
          total_tests=0
          for input_file in ../.github/workflows/testCases/input/*.txt; do
            total_tests=$((total_tests + 1))
            base_name=$(basename "$input_file" .txt)
            output_file="../.github/workflows/testCases/output/${base_name}.txt"
            result=$(./main < "$input_file")
            expected=$(cat "$output_file")
            if [ "$result" == "$expected" ]; then
              echo "Test $base_name passed"
              passed_tests=$((passed_tests + 1))
            else
              echo "Test $base_name failed. Expected: $expected, Got: $result"
            fi
          done
          echo "C++ tests: $passed_tests/$total_tests passed"
          if [ $passed_tests -eq $total_tests ]; then
            echo "All C++ tests passed!"
          else
            echo "Some C++ tests failed!"
            exit 1
          fi
        else
          echo "No C++ program found, skipping C++ tests."
        fi

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: java-test,cpp-test
